name: Check membership
inputs:
  organization-name:
    required: true
  member-name:
    required: true
  token:
    required: true
outputs:
  check-result:
    description: Membership check result
    value: ${{ steps.membership-check.outputs.check-result }}
runs:
  using: composite
  steps:
    - id: membership-check
      shell: bash
      run: |-
        if [[ "${{ inputs.organization-name }}" == "${{ inputs.member-name }}" ]] || gh api "orgs/${{ inputs.organization-name }}/members/${{ inputs.member-name }}"; then
          echo "check-result=true" >> ${GITHUB_OUTPUT}
        else
          echo "check-result=false" >> ${GITHUB_OUTPUT}
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
